// SPDX-License-Identifier: GPL-3.0-or-later

import AppKit

/// 定时检查剪贴板有没有变化，有新内容就记下来（C3、C4）。
///
/// macOS 没有剪贴板变化的通知，只能定时比较 changeCount。只在主线程上使用。
final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private let store: ClipboardStore
    private let config: () -> ClipboardConfig
    private var timer: Timer?
    private var lastChangeCount: Int
    /// 本程序自己写进剪贴板时的计数，看到它就不再记录。
    private var ownChangeCount: Int?

    /// 密码管理器等用这些类型标记“不要记录”（nspasteboard.org 的约定）。
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// 只记录这么大以内的内容，太大的跳过。
    static let maxTextBytes = 2 * 1024 * 1024
    static let maxImageBytes = 30 * 1024 * 1024
    static let maxExtraBytes = 2 * 1024 * 1024

    init(store: ClipboardStore, config: @escaping () -> ClipboardConfig) {
        self.store = store
        self.config = config
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.check() }
        t.tolerance = 0.1
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 本程序写完剪贴板后调用，避免把自己写的内容又记一遍。
    func noteOwnWrite() {
        ownChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    private func check() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        if count == ownChangeCount { return }

        let cfg = config()
        // 没有“始终允许”读取剪贴板时不读，否则每次复制都会弹出系统询问。
        guard cfg.enabled, PasteboardAccess.status == .allowed else { return }
        guard let capture = Self.capture(from: pasteboard, recordImages: cfg.recordImages) else { return }
        store.add(capture, maxItems: cfg.maxItems)
    }

    static func capture(from pasteboard: NSPasteboard, recordImages: Bool) -> ClipboardCapture? {
        guard let item = pasteboard.pasteboardItems?.first else { return nil }
        let types = Set(pasteboard.types?.map(\.rawValue) ?? [])
        if !types.isDisjoint(with: ignoredTypes) { return nil }
        // 在 Finder 里复制文件时剪贴板里是文件，Windows 的剪贴板历史也不记录文件。
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) { return nil }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if let text = item.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let utf8 = Data(text.utf8)
            guard utf8.count <= maxTextBytes else { return nil }
            var extras: [String: Data] = [:]
            for type in [NSPasteboard.PasteboardType.rtf, .html] {
                if let data = item.data(forType: type), data.count <= maxExtraBytes {
                    extras[type.rawValue] = data
                }
            }
            return ClipboardCapture(
                kind: .text, text: text, extras: extras,
                fingerprint: ClipboardStore.fingerprint([Data("text".utf8), utf8]),
                sourceApp: source
            )
        }

        guard recordImages else { return nil }
        let raw = item.data(forType: .png) ?? item.data(forType: .tiff)
        guard let raw, raw.count <= maxImageBytes,
              let rep = NSBitmapImageRep(data: raw),
              let png = item.data(forType: .png) ?? rep.representation(using: .png, properties: [:])
        else { return nil }
        return ClipboardCapture(
            kind: .image, text: nil, png: png,
            imageSize: CGSize(width: rep.pixelsWide, height: rep.pixelsHigh),
            fingerprint: ClipboardStore.fingerprint([Data("image".utf8), png]),
            sourceApp: source
        )
    }
}
